name: Build dm-verity Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-dmverity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install cryptsetup
        run: |
          sudo apt-get update
          sudo apt-get install -y cryptsetup

      - name: Create File System Image
        run: |
          echo "Creating a 100MB image file..."
          dd if=/dev/zero of=verity_data.img bs=1M count=100
          echo "Formatting image as ext4..."
          mkfs.ext4 verity_data.img

      - name: Populate Image with Test Data
        run: |
          mkdir -p mnt
          sudo mount -o loop verity_data.img mnt
          echo "Hello, dm-verity!" | sudo tee mnt/hello.txt > /dev/null
          sudo umount mnt

      - name: Generate dm-verity Hash Tree
        run: |
          echo "Running veritysetup format..."
          sudo veritysetup format verity_data.img verity_hash.img > verity_output.txt
          echo "Generated verity output:"
          cat verity_output.txt

      - name: Extract Root Hash
        run: |
          grep "Root hash:" verity_output.txt | awk '{print $3}' > roothash.txt
          echo "Extracted Root hash:"
          cat roothash.txt

      - name: Test dm-verity Mapping
        run: |
          echo "Creating dm-verity mapping..."
          sudo veritysetup create verity-mapped verity_data.img verity_hash.img $(cat roothash.txt)
          sudo mkdir -p mnt2
          sudo mount -o ro /dev/mapper/verity-mapped mnt2
          echo "Listing files in the mapped device:"
          ls -l mnt2
          sudo umount mnt2
          sudo veritysetup remove verity-mapped

      - name: Upload dm-verity Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dm-verity-artifacts
          path: |
            verity_data.img
            verity_hash.img
            verity_output.txt
            roothash.txt
            
